---
name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Use Node.js with versions ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Build, Lint, and Test
        run: |
          npm install
          npm run build
          npm run lint
          npm test
